### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by omahs**
fix typos

### CODE REVIEW

**Review by iainnash — APPROVED** [review]

**Review by oveddan — APPROVED** [review]
thanks for these fixes!

**Comment by oveddan** [comment]
there are also some typos [in this new contract](https://github.com/ourzora/zora-1155-contracts/blob/main/src/delegation/ZoraCreator1155PremintExecutorImpl.sol) if you want to take a stab at fixing them @omahs

**Comment by omahs** [comment]
@oveddan Hey, sure, I just checked and added them 👍

**Comment by oveddan** [comment]
> @oveddan Hey, sure, I just checked and added them 👍

thank you! looks great

**Pull request merged**
