### PR TITLE
Contract size optimization - remove unused royalty fetcher to reduce contract size

### PR DESCRIPTION
**Pull request by oveddan**

### CODE REVIEW

**Comment by oveddan** [comment]
Current dependencies on/for this PR:
* main
  * **PR #133** <a href="https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/133" target="_blank">Graphite</a> 
    * **PR #140** <a href="https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/140" target="_blank">Graphite</a>  👈
    * **PR #139** <a href="https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/139" target="_blank">Graphite</a> 
    * **PR #132** <a href="https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/132" target="_blank">Graphite</a> 
      * **PR #137** <a href="https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/137" target="_blank">Graphite</a> 
    * **PR #98** <a href="https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/98" target="_blank">Graphite</a> 
      * **PR #135** <a href="https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/135" target="_blank">Graphite</a> 
        * **PR #128** <a href="https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/128" target="_blank">Graphite</a> 
          * **PR #138** <a href="https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/138" target="_blank">Graphite</a> 
      * **PR #134** <a href="https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/134" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/140?utm_source=stack-comment).

**Review by iainnash — COMMENTED** [review]
I thought we used this on the contract level but I now realized we removed it. Did you check the front-end usage?

**Review by oveddan — COMMENTED** [review]
@mattlenz are you using the read method `supplyRoyaltyInfo` anywhere in the frontend? I didn't see it anywhere when searching the repo

**Review by iainnash — APPROVED** [review]

**Comment by iainnash** [comment]
Search looks good: https://github.com/search?q=org%3Aourzora%20supplyRoyaltyInfo&type=code

**Pull request merged**
