### PR TITLE
Premint - move attribution lib to contract consumed via interface

### PR DESCRIPTION
**Pull request by oveddan**

### CODE REVIEW

**Comment by oveddan** [comment]
Current dependencies on/for this PR:
* main
  * **PR #161** <a href="https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/161" target="_blank">Graphite</a> 
    * **PR #166** <a href="https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/166" target="_blank">Graphite</a>  👈
    * **PR #164** <a href="https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/164" target="_blank">Graphite</a> 
    * **PR #163** <a href="https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/163" target="_blank">Graphite</a> 
    * **PR #162** <a href="https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/162" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ourzora/zora-1155-contracts/166?utm_source=stack-comment).

**Comment by oveddan** [comment]
Runs into contract size limit...after this change, the size is now:
24.832
Before it was 
24.3

Not sure where this is coming from

**Comment by iainnash** [comment]
Did we fix the contract size issue on this? @oveddan

**Comment by iainnash** [comment]
Exploration diff – not meant to be merged.

**Pull request closed without merging**
