### PR TITLE
Adding base testnet

### PR DESCRIPTION
**Pull request by iainnash**

### CODE REVIEW

**Review by kulkarohan — APPROVED** [review]

**Comment by oveddan** [comment]
the following contracts are not verified:
factory proxy: https://goerli.basescan.org/address/0x9168c5ba5a0a76db8a1bf5b2ee5557f2a0eca4f4#code
factory impl: https://goerli.basescan.org/address/0x06e71de8a63c5392a15d06665c36184dbe78c85b#code

it looks like most of them arent actually

**Review by oveddan — CHANGES_REQUESTED** [review]
please try to verify the contracts

**Comment by iainnash** [comment]
the api is broken right now :/ base is aware

**Comment by oveddan** [comment]
contracts looking good! 

https://github.com/ourzora/zora-1155-contracts/actions/runs/5536629879/jobs/10104539315
Screenshot 2023-07-12 at 2 08 38 PM

**Review by oveddan — APPROVED** [review]

**Comment by oveddan** [comment]
fyi i added fork testing base testnet

**Comment by iainnash** [comment]
Added verifications.

**Pull request merged**
